version: '3'
services:
  
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
 

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmquser
      - RABBITMQ_DEFAULT_PASS=DEBmbwkSrzy9D1T9cJfa

  mailserver:
    image: djfarrelly/maildev
    container_name: mailserver
    ports:
      - "25:25"
      - "4000:80"

  logserver:
    image: datalust/seq:latest
    container_name: logserver
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y 

  customermanagementapihost:
    image: pitstoppro/customermanagementapihost:latest
    build: CustomerManagementAPI.Host
    depends_on:
      - rabbitmq
      - redis
      - logserver
      - mailserver
    volumes:
      - ${CERTIFICATE_PATH}:/root/.dotnet/https
    ports:
      - 5100:80
      - 5101:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_KESTREL_CERTIFICATE_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${ASPNETCORE_KESTREL_CERTIFICATE_PATH}
      - ASPNETCORE_HTTPS_PORT=5101

volumes:
  redisdata:
    external: true    
  rabbitmqdata:
    external: true